[package]
name = "orb-tui"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
orb-domain = { workspace = true }
orb-term = { workspace = true }
ratatui = { workspace = true }
wherror = { workspace = true }
error-stack = { workspace = true }
jiff = { workspace = true }
base64 = { workspace = true }
kameo = { workspace = true }
ratatui-which-key = { workspace = true }
tui-markdown = { workspace = true }
unicode-segmentation = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
