#!/bin/sh
# Writes orb's key maps to kitty's config directory as orb.conf and includes it
# from kitty.conf. Safe to run again: orb.conf is rewritten, the include is added once.
#
# macOS: Cmd keys are sent to orb as Super.
# Linux: the compositor usually owns Super, so Alt stands in for Cmd, only while
#        the focused kitty window's title starts with "orb" (fish, and bash/zsh
#        with kitty's shell integration, title the window after the running command).
#
# Reload kitty afterwards (ctrl+shift+F5 on Linux, ctrl+cmd+, on macOS).
set -eu

dir="${KITTY_CONFIG_DIRECTORY:-${XDG_CONFIG_HOME:-$HOME/.config}/kitty}"
keys='h j k l left down up right n x plus equal minus 1 2 3 4 5 6 7 8 9 [ ] i o'

mkdir -p "$dir"

case "$(uname -s)" in
Darwin)
	{
		echo '# Generated by orb scripts/kitty-keys.sh. Cmd keys reach orb as Super.'
		for k in $keys; do
			echo "map cmd+$k send_key super+$k"
		done
		echo
		echo '# kitty uses these itself; hand them to orb instead.'
		echo 'map ctrl+shift+h no_op'
		echo 'map ctrl+shift+l no_op'
	} >"$dir/orb.conf"
	;;
*)
	{
		echo '# Generated by orb scripts/kitty-keys.sh. The compositor owns Super,'
		echo '# so Alt stands in for Cmd while orb is focused.'
		for k in $keys; do
			echo "map --when-focus-on title:^orb alt+$k send_key super+$k"
		done
		echo
		echo '# kitty uses these itself (scrollback pager, next layout); hand them to orb instead.'
		echo 'map --when-focus-on title:^orb ctrl+shift+h send_key ctrl+shift+h'
		echo 'map --when-focus-on title:^orb ctrl+shift+l send_key ctrl+shift+l'
	} >"$dir/orb.conf"
	;;
esac

if ! grep -qx 'include orb.conf' "$dir/kitty.conf" 2>/dev/null; then
	printf '\n# orb keys\ninclude orb.conf\n' >>"$dir/kitty.conf"
fi

echo "wrote $dir/orb.conf; reload kitty to use it"
